version: "3.8"

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads # Map local uploads directory to container
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY} # Pass the OpenAI API key as an environment variable
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
